[package]
name = "jsl-validate"
version = "0.1.0"
authors = ["Ulysse Carion <ulysse@segment.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
failure = "0.1"
serde_json = "1.0"
jsl = "0.3"
serde = { version = "1.0", features = ["derive"] }
